### ISSUE TITLE
为啥被ban了，并没有重复执行 

### ISSUE THREAD

**Issue by juner922** [Zy143L/wskey#282]
使用 _id 键值

云端地址全部失效, 请检查网络!
WSKEY转换

云端地址失效. 请联系作者或者检查网络.

ip 221.232.12.228

**Comment by Mr-Coffee666** [comment]
我的也是这样
我提交的issue直接被作者close了。。。
也是很无语

**Comment by Mr-Coffee666** [comment]
这是因为被ban IP了吗？我也没有重复执行，一天就执行三轮而已

**Comment by Zy143L** [comment]
因为我没ban任何一个IP啊...
API监测也是正常的
服务器是HK+CF 请先考虑你当地运营商以及本地网络问题

**Comment by Zy143L** [comment]
我这边curl测试和拨测 17ce itdog测试均正常啊..

**Comment by Mr-Coffee666** [comment]
> 我这边curl测试和拨测 17ce itdog测试均正常啊..

搞不清楚了，之前一直用着好好的，突然就这样了

**Comment by Zy143L** [comment]
你尝试重启下青龙和容器 包括网络

**Comment by Mr-Coffee666** [comment]
> 你尝试重启下青龙和容器 包括网络

主机、光猫、路由、全断电重启过都没用

**Comment by Zy143L** [comment]
你浏览器能正常访问 api.momoe.ml吗

**Comment by Zy143L** [comment]
我找了四五个测试网站 均正常啊

**Comment by Mr-Coffee666** [comment]
![image](https://github.com/Zy143L/wskey/assets/66343425/0661ee1b-41bc-4055-990a-b87d1b0fb011)
![image](https://github.com/Zy143L/wskey/assets/66343425/f3d9b42d-42c8-41fe-829b-9087f5c40808)
![image](https://github.com/Zy143L/wskey/assets/66343425/3527f83a-f0b4-4fa8-bb74-92bd4108d755)

**Comment by Zy143L** [comment]
没让你ping啊... 我ping是关的 而且你本机解析的IP不对

**Comment by Mr-Coffee666** [comment]
我把代理关了，hosts全清空了，解析的IP还是这个

**Comment by Mr-Coffee666** [comment]
> 没让你ping啊... 我ping是关的 而且你本机解析的IP不对

您有空帮忙远程下么

**Comment by Zy143L** [comment]
我在练车..你可以看到上面图里面 网站解析结果都是43开头的IP
你本地网络 你可以尝试更换DNS测试

**Comment by Mr-Coffee666** [comment]
感谢感谢，换了114的dns就解决了

**Comment by juner922** [comment]
我是n1 青龙跑的脚本。。不知道咋解决了 重启路由 ip变了也不行 浏览器能正常访问 api.momoe.ml 提示{"code":200}

**Comment by Mr-Coffee666** [comment]
> 我是n1 青龙跑的脚本。。不知道咋解决了 重启路由 ip变了也不行 浏览器能正常访问 api.momoe.ml 提示{"code":200}

那你这情况和我的还不太一样，搞不清楚了，等作者大大回复吧

**Comment by Zy143L** [comment]
> 我是n1 青龙跑的脚本。。不知道咋解决了 重启路由 ip变了也不行 浏览器能正常访问 api.momoe.ml 提示{"code":200}

你在容器下curl一下不就知道了

**Comment by necan** [comment]
我怀疑你的IP被运营商墙了，我也是这几天出现这个问题的，换DNS无效。

**Comment by juner922** [comment]
> 
我是12还是13号出现的，主要n1里面 我也不知道docker怎么扶梯。现在不能自动转换太麻烦了

**Comment by juner922** [comment]
> 我怀疑你的IP被运营商墙了，我也是这几天出现这个问题的，换DNS无效。

我是12还是13号出现的，主要n1里面 我也不知道docker怎么扶梯。现在不能自动转换太麻烦了

**Comment by necan** [comment]
我搞清楚了 api.momoe.ml 这个主机已经被运营商 DNS 污染了，还是得改 DNS，docker 配置如下：
```yaml
version: "3"
services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    restart: unless-stopped
    tty: true
    dns:
      - 114.114.114.114
      - 180.76.76.76
      - 114.114.115.115
      - 101.226.4.6
    ports:
      - 5700:5700
    environment:
      - TZ=PRC
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true
    volumes:
      - ./data:/ql/data
      - ./config/pip.conf:/etc/pip.conf
    labels:
      - com.centurylinklabs.watchtower.enable=false
```
